#include <stdio.h>

using namespace std;

class Process{

private:
    int rank; // Generated by MPI
    bool active; // Is Process active or passive

public:
    // Default Constructor
    Process(int rk){
        rank =rk;
        active = true;
    }

    // Simple functions for accessing private variables
    int getRank(){
        return rank;
    }
    bool isActive(){
        return active;
    }
    void setActive(bool status){
        active = status;
    }
};